-- create
CREATE TABLE STYDENTS (
  Id INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  age TEXT NOT NULL,
  address TEXT NOT NULL
);

-- insert
INSERT INTO STYDENTS VALUES (0001, 'Anna', '18', 'SPB');
INSERT INTO STYDENTS VALUES (0002, 'Dave', '25', 'Moscow');
INSERT INTO STYDENTS VALUES (0003, 'Andrey', '35', 'Moscow');
INSERT INTO STYDENTS VALUES (0004, 'Sonya', '37', 'SPB');
INSERT INTO STYDENTS VALUES (0005, 'Alex', '39', 'Sochi');
INSERT INTO STYDENTS VALUES (0006, 'Denis', '37', 'Moscow');
INSERT INTO STYDENTS VALUES (0007, 'Alex', '31', 'Samara');
INSERT INTO STYDENTS VALUES (0008, 'Andrey', '32', 'Novgorod');

-- select
SELECT* FROM STYDENTS;